# Generated by Django 5.1.2 on 2024-11-28 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingamenity',
            name='duration_booked',
        ),
        migrations.AddField(
            model_name='bookingamenity',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookingamenity',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
