export const metadata = {
  title: 'Managy',
  description: 'Generated by Javier Tarazona, Davis Ernst, ' +
      'Alyssa Amadora, Robert Chantry, Rosemary Fache',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <base href="/"/>
      <link rel="icon" href="/favicon.ico" sizes="any"/>
    </head>
    <body>{children}</body>
    </html>
  )
}
